"""
Imports the data from the CSV file generated by Qualtrics.
Any entires already in the database are ignored during the import.
"""
import sys
import csv
import records

JUDGE_ROLE_NUM = '1'
MENTOR_ROLE_NUM = '2'

# Variable to keep track of stats for report at the end.
num_duplicates = 0
num_error = 0
num_unfinished = 0
num_entries = 0

#TODO this only works with leaders, need to make it work for participants

with open(sys.argv[1], 'r') as csv_file:
    # Try to open the provided file name.
    try:
        reader = csv.DictReader(csv_file, delimiter=",")
    except:
        raise BaseException("Cannot read/import csv file. Check format and resubmit.")
    
    # For each entry in the CSV file...
    for entry in reader:
        num_entries = num_entries + 1

        ### Collect data. ###
        # Check that the entry is for a completed response.
        if entry['Progress'] != '100':
            num_unfinished = num_unfinished + 1
            continue

        # Check for and store the entry's first name.
        if entry['First Name'] == '':
            num_error = num_error + 1
            continue
        first_name = entry['First Name']

        # Check for and store the entry's email.
        if entry['Email'] == '':
            num_error = num_error + 1
            continue
        email = entry['Email']

        # Check for a roles attribute.
        roles = []
        try:
            if entry['Roles'] == '':
                # If the roles attribute exists but is blank,
                # skip this entry.
                num_error = num_error + 1
                continue
            # Add appropriate roles for the volunteer form.
            if entry['Roles'].find(JUDGE_ROLE_NUM) != -1:
                roles.append('judge')
            if entry['Roles'].find(MENTOR_ROLE_NUM) != -1:
                roles.append('mentor')
        except KeyError:
            # If the roles attribute does not exist,
            # then we are importing the participant form.
            roles.append('participant')

        ### Add data to database. ###
        #TODO check if entry already exists
        #TODO add entry to DB

print(f'Finished importing {sys.argv[1]}')
