"""
Imports the data from the CSV file generated by Qualtrics.
Any entires already in the database are ignored during the import.
"""
import sys
import csv
import records
import time

# Be sure to check the Qualtrics forms for what these values should be.
JUDGE_ROLE_NUM = '1'
"""A string that represents the judge role in the volunteer form's CSV file."""
MENTOR_ROLE_NUM = '2'
"""A string that represents the mentor role in the volunteer form's CSV file."""

# Variable to keep track of stats for report at the end.
num_duplicates = 0
num_error = 0
num_unfinished = 0
num_entries = 0
start_time = time.time()

# Check that the correct number of command line arguments were given.
try:
    assert len(sys.argv) == 2
except AssertionError:
    print('USAGE: import_table.py [csv_filename]')
    print('csv_filename: the name of the CSV file to import.')
    sys.exit(2)

# Print a startup message.
print(f'Started importing {sys.argv[1]}, please wait...')

with open(sys.argv[1], 'r', encoding='utf-8') as csv_file:
    # Try to open the provided file name.
    try:
        assert sys.argv[1].lower().endswith('.csv')
        reader = csv.DictReader(csv_file, delimiter=',')
    except AssertionError:
        print('ERROR: Not a CSV file. Check format and resubmit.')
        sys.exit(2)

    # Verify that the file has all the attributes we need.
    try:
        attributes = set(reader.fieldnames)
        attributes.remove('Progress')
        attributes.remove('Email')
        attributes.remove('First Name')
        attributes.remove('Last Name')
    except TypeError:
        print('ERROR: CSV file not formatted correctly. Check file contents and resubmit.')
        sys.exit(2)
    except KeyError:
        print('ERROR: CSV file missing required attributes. Check file contents and resubmit.')
        sys.exit(2)

    # Check if we are importing the participant or volunteer form.
    is_participant = False
    try:
        attributes.remove('Roles')
    except KeyError:
        is_participant = True

    # Verify that the participant form has all the attributes we need.
    try:
        if is_participant:
            attributes.remove('Capstone Team')
    except KeyError:
        print('ERROR: CSV file missing required attributes. Check file contents and resubmit.')
        sys.exit(2)

    # For each entry in the CSV file...
    for entry in reader:
        num_entries = num_entries + 1

        # Check that the entry is for a completed response.
        if entry['Progress'] != '100':
            num_unfinished = num_unfinished + 1
            continue

        # Check for and store the entry's email.
        if entry['Email'] == '':
            num_error = num_error + 1
            continue
        email = entry['Email'].replace(' ', '').lower()

        # If this person is a participant, check if they are on a capstone team.
        is_capstone = entry['Capstone Team'] == 'Yes' if is_participant else False

        # Check for and store the entry's roles.
        roles = []
        if is_participant:
            roles.append('participant')
        else:
            # If the roles attribute exists but is blank, skip this entry.
            if entry['Roles'] == '':
                num_error = num_error + 1
                continue
            # Add appropriate roles for the volunteer form.
            if JUDGE_ROLE_NUM in entry['Roles']:
                roles.append('judge')
            if MENTOR_ROLE_NUM in entry['Roles']:
                roles.append('mentor')

        # Add this entry's data to the database if it is not a duplicate.
        if records.is_registered(email):
            # Get the existing version of this entry's data.
            old_data = records.get_registration(email)

            # Check if the names are the same.
            is_duplicate = old_data['first_name'] == entry['First Name']
            is_duplicate = is_duplicate and old_data['last_name'] == entry['Last Name']

            # Check if the capstone team status is the same.
            if is_participant:
                is_duplicate = is_duplicate and old_data['is_capstone'] == (entry['Capstone Team'] == 'Yes')

            # Check if the roles are the same.
            is_duplicate = is_duplicate and set(records.get_user_roles(email)) == set(roles)

            # If this entry is not a duplicate, add it.
            if not is_duplicate:
                records.add_registration(email, entry['First Name'], entry['Last Name'], is_capstone, roles)
            else:
                num_duplicates = num_duplicates + 1
        else:
            # If this entry is not in the database, add it.
            records.add_registration(email, entry['First Name'], entry['Last Name'], is_capstone, roles)

# There are essentially three header rows in the CSV file generated by Qualtrics.
# One header row is the actual header row, and the other two rows are treated as entries
# by the CSV reader. As such, subtract two from the relevant totals.
num_entries = num_entries - 2
num_unfinished = num_unfinished - 2

# Output statistics to help with any troubleshooting that may come up.
print(f'Finished importing {sys.argv[1]}')
print(f'Processing time: {time.time() - start_time:.3f} seconds')
print(f'Total number of entries processed: {num_entries}')
print(f'-----------------------------------------')
print(f'Number of entries added to database:', end=' ')
print(f'{num_entries - num_duplicates - num_error - num_unfinished} out of {num_entries}')
print(f'Number of duplicate entries: {num_duplicates} out of {num_entries}')
print(f'Number of entries with incomplete information: {num_error} out of {num_entries}')
print(f'Number of unfinished entries: {num_unfinished} out of {num_entries}')
